import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    bestSelling: true,
    brandName: "Woodland",
    productName: "Leather Camel Sneakers",
    mrp: 2499,
    offer: 15,
    price: "",
    categoryName: "SNEAKERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342437/woodland-sneaker-camel_aegumr.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.5",
    description: "Leather camel sneakers for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Woodland",
    productName: "Leather Gray Sneakers",
    mrp: 2299,
    offer: 15,
    price: "",
    categoryName: "SNEAKERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342435/woodland-casual-blue_w864uz.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.2",
    description: "Leather gray sneakers for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Woodland",
    productName: "Funky Sneakers",
    mrp: 3999,
    offer: 20,
    price: "",
    categoryName: "SNEAKERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697363085/woodland-sports-blue_kwlvo6.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.2",
    description: "Funky Sneakers for men",
  },
  {
    _id: uuid(),
    bestSelling: true,
    brandName: "Woodland",
    productName: "Leather Navy Slip-On",
    mrp: 1999,
    offer: 10,
    price: "",
    categoryName: "CASUALS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697362804/woodland-casual-navy_y88ixr.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.2",
    description: "Leather navy slip-on for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Woodland",
    productName: "Leather Tan Loafer",
    mrp: 1799,
    offer: 10,
    price: "",
    categoryName: "LOAFERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697362803/woodland-loafer-biege_mjlanr.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.2",
    description: "Leather tan loafer for men",
  },
  {
    _id: uuid(),
    bestSelling: true,
    brandName: "Woodland",
    productName: "Brown Formal Shoe",
    mrp: 2199,
    offer: 15,
    price: "",
    categoryName: "FORMALS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697362803/woodland-formal-brwn_o7cwe3.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.5",
    description: "Brown formal shoe for men",
  },
  {
    _id: uuid(),
    bestSelling: true,
    brandName: "Woodland",
    productName: "Cashew Brown Sneakers",
    mrp: 2499,
    offer: 20,
    price: "",
    categoryName: "SNEAKERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342438/woodland-sneaker-cashewbrn_johwog.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.2",
    description: "Cashew brown sneakers for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Woodland",
    productName: "Grey Sneakers",
    mrp: 1799,
    offer: 10,
    price: "",
    categoryName: "SNEAKERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342441/woodland-sneaker-olive_c1vmrv.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.1",
    description: "Gray sneakers for men",
  },
  {
    _id: uuid(),
    bestSelling: true,
    brandName: "Woodland",
    productName: "Navy Sneakers",
    mrp: 2299,
    offer: 10,
    price: "",
    categoryName: "SNEAKERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342439/woodland-sneaker-navy_szsjvf.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.2",
    description: "Navy sneakers for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Woodland",
    productName: "Navy Boots",
    mrp: 2999,
    offer: 20,
    price: "",
    categoryName: "BOOTS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342434/woodland-boot-navy_psbkjx.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.0",
    description: "Navy boots for men",
  },
  {
    _id: uuid(),
    bestSelling: true,
    brandName: "Woodland",
    productName: "Camel Boots",
    mrp: 2299,
    offer: 15,
    price: "",
    categoryName: "BOOTS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342436/woodland-casual-camel_dv09nn.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.3",
    description: "Camel boots for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Bata",
    productName: "Leather Black Loafers",
    mrp: 2199,
    offer: 10,
    price: "",
    categoryName: "LOAFERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342428/bata-loafer-leather-black_u4vwqh.jpg",
    size: ["7", "8", "9", "10"],
    rating: "4.4",
    description: "Leather black for men",
  },
  // {
  //   _id: uuid(),
  //   bestSelling: true,
  //   brandName: "Woodland",
  //   productName: "Navy Sneakers",
  //   mrp: 2299,
  //   offer: 10,
  //   price: "",
  //   categoryName: "SNEAKERS",
  //   img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342439/woodland-sneaker-navy_szsjvf.webp",
  //   size: ["7", "8", "9", "10"],
  //   rating: "4.2",
  //   description: "Navy sneakers for men",
  // },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Bata",
    productName: "Brown Leather Loafers",
    mrp: 1999,
    offer: 10,
    price: "",
    categoryName: "LOAFERS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342426/bata-loafer-brown_mpfqa5.jpg",
    size: ["7", "8", "9", "10"],
    rating: "4.1",
    description: "Brown leather loaders for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Bata",
    productName: "Tan Formal Shoe",
    mrp: 2299,
    offer: 15,
    price: "",
    categoryName: "FORMALS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342424/bata-formal-tan_mninnt.jpg",
    size: ["7", "8", "9", "10"],
    rating: "4.8",
    description: "Tan formal shoe for men",
  },

  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Bata",
    productName: "Brown Formal Shoes",
    mrp: 2299,
    offer: 15,
    price: "",
    categoryName: "FORMALS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342423/bata-formal-brown_ejeutx.jpg",
    size: ["7", "8", "9", "10"],
    rating: "4.6",
    description: "Brown formal shoes for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Bata",
    productName: "Black Formal Shoes",
    mrp: 2299,
    offer: 15,
    price: "",
    categoryName: "FORMALS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342421/bata-formal-black_cvruzb.jpg",
    size: ["7", "8", "9", "10"],
    rating: "4.3",
    description: "Black formal shoes for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Abros",
    productName: "Navy Walking Shoe",
    mrp: 1299,
    offer: 10,
    price: "",
    categoryName: "CASUALS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342411/abros-walking-navyneon_xgnnlq.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.2",
    description: "Navy walking shoe for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Abros",
    productName: "Biege Walking Shoe",
    mrp: 1299,
    offer: 10,
    price: "",
    categoryName: "CASUALS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342409/abros-walking-biege_abjh10.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.0",
    description: "Biege walking shoe for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Abros",
    productName: "Grey Sports Shoe",
    mrp: 1499,
    offer: 10,
    price: "",
    categoryName: "SPORTS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342407/abros-sports-grey_jcgkt2.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.4",
    description: "Grey sports shoe for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Abros",
    productName: "Black and Grey Walking Shoe",
    mrp: 1299,
    offer: 10,
    price: "",
    categoryName: "CASUALS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342410/abros-walking-black_xmjdrs.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.7",
    description: "Black and Grey walking shoe for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Abros",
    productName: "Grey Tan Sports Shoe",
    mrp: 1499,
    offer: 10,
    price: "",
    categoryName: "SPORTS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342408/abros-sports-greytan_uwmk2v.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.6",
    description: "Grey tan sports shoe for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Abros",
    productName: "Biege Sports Shoe",
    mrp: 1499,
    offer: 10,
    price: "",
    categoryName: "SPORTS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342406/abros-sports-beige_omfcka.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.1",
    description: "Biege sports shoe for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Abros",
    productName: "Grey Sports Shoe",
    mrp: 1499,
    offer: 10,
    price: "",
    categoryName: "SPORTS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342399/abros-casual-grey_igwab2.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.2",
    description: "Grey sports shoe for men",
  },
  {
    _id: uuid(),
    bestSelling: false,
    brandName: "Abros",
    productName: "White Sports Shoe",
    mrp: 1499,
    offer: 10,
    price: "",
    categoryName: "SPORTS",
    img: "https://res.cloudinary.com/dewisedrc/image/upload/v1697342396/abros-boys-casual-grey_pmp49d.webp",
    size: ["7", "8", "9", "10"],
    rating: "4.3",
    description: "White sports shoe for men",
  },
];
